### ISSUE TITLE
[flightgear] fgelev build error

### ISSUE THREAD

**Issue by Hacker1245** [acxz/flightgear-arch#5] opened 2022-11-16 12:01 UTC
```
[ 10%] Building CXX object utils/fgelev/CMakeFiles/fgelev.dir/fgelev.cxx.o
In file included from /home/kacper/.cache/yay/flightgear/src/flightgear-2020.3.13/utils/fgelev/fgelev.cxx:30:
/usr/include/simgear/props/props.hxx:1397:18: error: ‘shared_mutex’ in namespace ‘std’ does not name a type
 1397 |     mutable std::shared_mutex _mutex;
      |                  ^~~~~~~~~~~~
/usr/include/simgear/props/props.hxx:1397:13: note: ‘std::shared_mutex’ is only available from C++17 onwards
 1397 |     mutable std::shared_mutex _mutex;
      |             ^~~
make[2]: *** [utils/fgelev/CMakeFiles/fgelev.dir/build.make:76: utils/fgelev/CMakeFiles/fgelev.dir/fgelev.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1899: utils/fgelev/CMakeFiles/fgelev.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: flightgear
```

**Comment by WalterSmuts** [comment] 2023-01-27 15:19
Manually pulling the simgear repo and building that worked for me.

**Comment by acxz** [comment] 2023-03-22 15:16
After the recent update I am not able to reproduce this error. As such closing this issue.

**Closed as completed by acxz** 2023-03-22 15:16 UTC
Labels: build error
