### ISSUE TITLE
src/flightgear-2020.3.17/utils/fgelev/fgelev.cxx:30: /usr/include/simgear/props/props.hxx:1403:18: error: ‘shared_mutex’ in namespace ‘std’ does not name a type 1403 | mutable std::shared_mutex _mutex;

### ISSUE THREAD

**Issue by simona70** [acxz/flightgear-arch#13] opened 2023-12-31 09:29 UTC
In file included from /home/simona/.cache/yay/flightgear/src/flightgear-2020.3.17/utils/fgelev/fgelev.cxx:30:
/usr/include/simgear/props/props.hxx:1403:18: error: ‘shared_mutex’ in namespace ‘std’ does not name a type
1403 | mutable std::shared_mutex _mutex;
| ^~~~~~~~~~~~
/usr/include/simgear/props/props.hxx:1403:13: note: ‘std::shared_mutex’ is only available from C++17 onwards
1403 | mutable std::shared_mutex _mutex;
| ^~~
make[2]: [utils/fgelev/CMakeFiles/fgelev.dir/build.make:76: utils/fgelev/CMakeFiles/fgelev.dir/fgelev.cxx.o] Error 1
make[1]: [CMakeFiles/Makefile2:2693: utils/fgelev/CMakeFiles/fgelev.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by acxz** [comment] 2023-12-31 16:02
duplicate of #11

**Closed as completed by acxz** 2023-12-31 16:02 UTC
